import "./styles/main.scss";
import "./static/img/logo.png";
import "./static/img/estrellas.png";
import "./static/img/search.svg";
import "./static/img/pastel3.jpg";
import "./static/img/torta1.png";
import "./static/img/facebook.svg";
import "./static/img/instagram.svg";
import "./static/img/twitter.svg";
